version: '3'
services:
  app:
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo
    command: ["mongod", "--quiet"]
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: